development:
  theme_id: '159401539'
  store: spinellikilcollin.myshopify.com
  timeout: 60s
  ignore_files:
    - node_modules/
    - src/
    - .git/
    - package.json
    - _working/
    - gulpfile.js
    - config/settings_data.json
    - backstop.json
    - backstop_data
production:
  theme_id: '160214531'
  store: spinellikilcollin.myshopify.com
  timeout: 60s
  ignore_files:
    - node_modules/
    - src/
    - .git/
    - package.json
    - _working/
    - gulpfile.js
    - config/settings_data.json
    - backstop.json
    - backstop_data
