development-archive:
  password: 1655af638136d9a8b53e608d7528e639
  theme_id: "156385027"
  store: spinellikilcollin.myshopify.com
  ignore_files:
    - node_modules/
    - src/
    - .git/
    - package.json
    - _working/
    - gulpfile.js
production-archive:
  password: 1655af638136d9a8b53e608d7528e639
  theme_id: "91902467"
  store: spinellikilcollin.myshopify.com
  timeout: 60s
  ignore_files:
    - node_modules/
    - src/
    - .git/
    - package.json
    - _working/
    - gulpfile.js
development:
  password: 1655af638136d9a8b53e608d7528e639
  theme_id: "159401539"
  store: spinellikilcollin.myshopify.com
  timeout: 60s
  ignore_files:
    - node_modules/
    - src/
    - .git/
    - package.json
    - _working/
    - gulpfile.js
production:
  password: 1655af638136d9a8b53e608d7528e639
  theme_id: "160214531"
  store: spinellikilcollin.myshopify.com
  timeout: 60s
  ignore_files:
    - node_modules/
    - src/
    - .git/
    - package.json
    - _working/
    - gulpfile.js
